# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "27fd3927f3f2c74542c87ee917654c33"
name = "HideShipmentProvider"
handle = "hideshipmentprovider"
application_url = "https://hunter-defensive-tennis-tennessee.trycloudflare.com"
embedded = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[auth]
redirect_urls = [
  "https://hunter-defensive-tennis-tennessee.trycloudflare.com/auth/callback",
  "https://hunter-defensive-tennis-tennessee.trycloudflare.com/auth/shopify/callback",
  "https://hunter-defensive-tennis-tennessee.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_orders,read_customers"

[development]
use_localhost = true
