# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "27fd3927f3f2c74542c87ee917654c33"
name = "HideShipmentProvider"
handle = "hideshipmentprovider"
application_url = "https://signs-ebook-deadly-sa.trycloudflare.com"
embedded = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[auth]
redirect_urls = [
  "https://signs-ebook-deadly-sa.trycloudflare.com/auth/callback",
  "https://signs-ebook-deadly-sa.trycloudflare.com/auth/shopify/callback",
  "https://signs-ebook-deadly-sa.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
